"""resume file metadata

Revision ID: dcdcd5f597e9
Revises: 2d5d40a70ca5
Create Date: 2026-09-21 21:52:53.612674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcdcd5f597e9'
down_revision: Union[str, None] = '2d5d40a70ca5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('file_name', sa.Text(), server_default='resume', nullable=False))
    op.add_column('resumes', sa.Column('content_type', sa.Text(), server_default='application/octet-stream', nullable=False))
    op.add_column('resumes', sa.Column('size_bytes', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'size_bytes')
    op.drop_column('resumes', 'content_type')
    op.drop_column('resumes', 'file_name')
    # ### end Alembic commands ###
