"""add company_name to job_sources

Revision ID: 2d5d40a70ca5
Revises: 101f0b7f38d2
Create Date: 2026-09-21 11:56:04.500430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d5d40a70ca5'
down_revision: Union[str, None] = '101f0b7f38d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_sources', sa.Column('company_name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_sources', 'company_name')
    # ### end Alembic commands ###
